<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
import numpy as np
import random

sample=[random.randrange(1,100)for i in range (9)]
arr1=np.array(sample)
arr2=arr1.reshape(3,3)
print(arr2)

[[22  3 74]
 [76 35 70]
 [64 98 80]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np
import random

sample1=[random.randrange(1,100)for i in range (16)]
sample2=[random.randrange(1,100)for i in range (16)]
arr11=np.array(sample1)
arr22=np.array(sample2)
newarr11=arr11.reshape(4,4)
newarr22=arr22.reshape(4,4)
print(" 4x4 matrix A is ")
print(newarr11 ,"\n")
print(" 4x4 matrix B is  ")
print(newarr22,"\n")
newarr111=newarr11.reshape(2,8)
newarr222=newarr22.reshape(2,8)
print("Rerranged 2x8 matrix of A is ")
print(newarr111,"\n")
print("Rerranged 2x8 matrix of B is ")
print(newarr222,"\n")
hoz1=np.hstack((newarr111,newarr222))
ver1=np.vstack((newarr111,newarr222))

print("Horizontal stack of rearranged matrices A and B is ")
print(hoz1,"\n")

print("Vertical stack of  rearranged matrices A and B is ")
print(ver1)


 4x4 matrix A is 
[[17 97 54 89]
 [17 76 71 72]
 [93 91 84 85]
 [96 97 49 64]] 

 4x4 matrix B is  
[[43 66 21 35]
 [94 63  1 22]
 [ 4 40 50 89]
 [12 11 33 38]] 

Rerranged 2x8 matrix of A is 
[[17 97 54 89 17 76 71 72]
 [93 91 84 85 96 97 49 64]] 

Rerranged 2x8 matrix of B is 
[[43 66 21 35 94 63  1 22]
 [ 4 40 50 89 12 11 33 38]] 

Horizontal stack of rearranged matrices A and B is 
[[17 97 54 89 17 76 71 72 43 66 21 35 94 63  1 22]
 [93 91 84 85 96 97 49 64  4 40 50 89 12 11 33 38]] 

Vertical stack of  rearranged matrices A and B is 
[[17 97 54 89 17 76 71 72]
 [93 91 84 85 96 97 49 64]
 [43 66 21 35 94 63  1 22]
 [ 4 40 50 89 12 11 33 38]]
