<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK%2014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create two arrays, one containing elements [1,2], [3,4] and another containing elements [8,18] Now find the solution for this linear equation.

In [1]:
#please type your answer below this line.
import numpy as np

a = np.array(([1,2], [3,4]))
b = np.array([8,18])
print("Array A is \n",a,"\n")
print("Array B is \n",b,"\n")
print("Solution of linear equations A and B is \n", np.linalg.solve(a , b))



Array A is 
 [[1 2]
 [3 4]] 

Array B is 
 [ 8 18] 

Solution of linear equations A and B is 
 [2. 3.]


2. Create an array containing elements [2, 3, 4]. Now find the sin,cos,tan values of this array elements.

In [2]:
#please type your answer below this line.

import numpy as np
a= np.array([2,3,4])
print("Array A is \n",a,"\n")
#the sin,cos,tan functions only work on radians 
#so the inputs should be converted to radians
print("Converted array in radians is \n",a*(np.pi/180),"\n")
#np.pi is the constant pi in numpy
print("Sin value of A is \n",np.sin(a),"\n")
print("Cos value of A is \n",np.cos(a),"\n")
print("Tan value of A is \n",np.tan(a))

Array A is 
 [2 3 4] 

Converted array in radians is 
 [0.03490659 0.05235988 0.06981317] 

Sin value of A is 
 [ 0.90929743  0.14112001 -0.7568025 ] 

Cos value of A is 
 [-0.41614684 -0.9899925  -0.65364362] 

Tan value of A is 
 [-2.18503986 -0.14254654  1.15782128]


3. Given b=[5,6], then find,

  a) 2sinb
  b) 2cos3b
  c) 4tan2b

In [5]:
#please type your answer below this line.
import numpy as np

b = np.array([5,6])
b = b*np.pi/180
print("Changed array into radians \n",b,"\n")
print("Value of 2sinb is \n",2*np.sin(b),"\n")
print("Value of 2cos3b is \n",2*np.cos(3*b),"\n")
print("Value of 4tan2b is \n",4*np.tan(2*b))

Changed array into radians 
 [0.08726646 0.10471976] 

Value of 2sinb is 
 [0.17431149 0.20905693] 

Value of 2cos3b is 
 [1.93185165 1.90211303] 

Value of 4tan2b is 
 [0.70530792 0.85022625]
