<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
import random

sample=[random.randrange(1,100)for i in range (9)]
arr1=np.array(sample)
arr2=arr1.reshape(3,3)
print(arr2)

[[97 52 92]
 [ 4 61 40]
 [89 60 96]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [8]:
import numpy as np
import random

sample=[random.randrange(1,100)for i in range (16)]
arr1=np.array(sample)
newarr=arr1.reshape(4,4)
print("4x4 matrix  ")
print(newarr)
print()
newarr1=newarr.reshape(2,8)
print("2x8 matrix  ")
print(newarr1)
print()
hoz=np.hstack(newarr1)
ver=np.vstack(newarr1)

print("horizontal stack ")
print(hoz)
print()
print("vertical stack ")
print(ver)
print()

4x4 matrix  
[[65 77 72 78]
 [62 98  9 88]
 [29 48 42 38]
 [54 87 63 39]]

2x8 matrix  
[[65 77 72 78 62 98  9 88]
 [29 48 42 38 54 87 63 39]]

horizontal stack 
[65 77 72 78 62 98  9 88 29 48 42 38 54 87 63 39]

vertical stack 
[[65 77 72 78 62 98  9 88]
 [29 48 42 38 54 87 63 39]]

