<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK%2010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [6]:
#please provide your answer below this line.
import numpy
a = numpy.arange(5,14).reshape(3,3)
b = numpy.arange(20,29).reshape(3,3)
dot = numpy.dot(a, b)
t = dot.transpose()
print("Matrix a is \n",a)
print("Matrix b is \n",b)
print("Dot product of a and b is \n",dot)
print("Transpose of a and b is \n",t)


Matrix a is 
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Matrix b is 
 [[20 21 22]
 [23 24 25]
 [26 27 28]]
Dot product of a and b is 
 [[420 438 456]
 [627 654 681]
 [834 870 906]]
Transpose of a and b is 
 [[420 627 834]
 [438 654 870]
 [456 681 906]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [7]:
#please provide your answer below this line.
import numpy
a = numpy.array([55,25,15,30,44,2,11,45,77]).reshape(3,3)
print("The matrix a is \n",a)
print("Determinant of a is \n",numpy.linalg.det(a))

The matrix a is 
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant of a is 
 137180.0000000001
