<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK%2013.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [2]:
#please enter your code below this line.
import numpy as np
a = np.arange(0,9).reshape(3,3)
print("Matrix A is \n",a,"\n")
print("Sum of elements in A is ",a.sum())

Matrix A is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Sum of elements in A is  36


2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [3]:
#please enter your code below this line.
import numpy as np
a = np.arange(0,9).reshape(3,3)
print("Matrix A is \n",a,"\n")
coloumnsum= np.sum(a, axis = 0)
print("Sum of all the columns is \n", coloumnsum,"\n")
rowsum= np.sum(a, axis = 1)
print("Sum of all the rows is \n", rowsum)


Matrix A is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Sum of all the columns is 
 [ 9 12 15] 

Sum of all the rows is 
 [ 3 12 21]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [4]:
#please enter your code belowthis line.
import numpy as np
a = np.arange(0,16).reshape(4,4)
print("Matrix A is \n",a,"\n")
print("Element with minimum value in A is \n",np.min(a),"\n")
print("Element with maximum value in A is \n", np.max(a),"\n")
print("Mean of values of A is \n", np.mean(a))


Matrix A is 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

Element with minimum value in A is 
 0 

Element with maximum value in A is 
 15 

Mean of values of A is 
 7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [6]:
#please enter your code below this line.
import numpy as np
a = np.arange(0,100).reshape(10,10)
print("Matrix A is \n",a,"\n")
print("The 7 th row of A is \n",a[6],"\n")
print("Rows from 4 to 8 of A is \n",a[3:8],"\n")
print("The element at 5,5 is  \n",a[5][5],"\n")
print("The 5 th column of A is \n",a[:,4],"\n")
print("The columns from 2 to 5 of A  is \n",a[ : , 1:5])


Matrix A is 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 

The 7 th row of A is 
 [60 61 62 63 64 65 66 67 68 69] 

Rows from 4 to 8 of A is 
 [[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]] 

The element at 5,5 is  
 55 

The 5 th column of A is 
 [ 4 14 24 34 44 54 64 74 84 94] 

The columns from 2 to 5 of A  is 
 [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]
 [81 82 83 84]
 [91 92 93 94]]
