<a href="https://colab.research.google.com/github/coding-sorcerer-1/LEARN.PY/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [3]:
#please type your answer below this line.
import numpy as np
import pandas as pd
datetime = pd.date_range('2021-08-24',periods=4)
x = pd.DataFrame(np.random.randn(4,4), index=datetime, columns=list('ABCD'))
print("Head ")
print(x.head(),"\n")
print("Tail ")
print(x.tail(),"\n")
print("Index ")
print(x.index,"\n")
print("Columns ")
print(x.columns,"\n")
print("Values ")
print(x.values,"\n")
print("Statistics ")
print(x.describe(),"\n")

Head 
                   A         B         C         D
2021-08-24  0.421877 -0.200039 -0.236355 -0.371284
2021-08-25  0.165848 -0.761007 -2.224645  0.923465
2021-08-26  1.020591  0.079978 -0.081378  1.004786
2021-08-27 -0.227813  1.773181  0.789048  1.138915 

Tail 
                   A         B         C         D
2021-08-24  0.421877 -0.200039 -0.236355 -0.371284
2021-08-25  0.165848 -0.761007 -2.224645  0.923465
2021-08-26  1.020591  0.079978 -0.081378  1.004786
2021-08-27 -0.227813  1.773181  0.789048  1.138915 

Index 
DatetimeIndex(['2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27'], dtype='datetime64[ns]', freq='D') 

Columns 
Index(['A', 'B', 'C', 'D'], dtype='object') 

Values 
[[ 0.42187744 -0.20003945 -0.23635529 -0.37128415]
 [ 0.16584848 -0.76100739 -2.22464541  0.92346497]
 [ 1.02059101  0.07997755 -0.08137817  1.00478581]
 [-0.22781334  1.77318126  0.78904843  1.13891513]] 

Statistics 
              A         B         C         D
count  4.000000  4.000000  4.00

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [2]:
#please provide your answer below this line.
print("Transpose")
print(x.transpose(),"\n")
print("Descending Order ")
print(x.sort_index(ascending=False))

Transpose
   2021-08-24  2021-08-25  2021-08-26  2021-08-27
A    0.522189    0.370678    0.233585    1.000028
B   -0.388090   -1.092135   -0.986084   -0.395187
C   -2.211833    0.992360   -1.176834    0.738532
D   -0.434990    2.103375   -0.240729    1.371093 

Descending Order 
                   A         B         C         D
2021-08-27  1.000028 -0.395187  0.738532  1.371093
2021-08-26  0.233585 -0.986084 -1.176834 -0.240729
2021-08-25  0.370678 -1.092135  0.992360  2.103375
2021-08-24  0.522189 -0.388090 -2.211833 -0.434990
